### ISSUE TITLE
Would it be a good idea to offer regular snapshots of the libs?

### ISSUE THREAD

**Issue by poeschlr** [KiCad/kicad.github.io#15]
Just a stupid idea i had to allow people to easily download past states of the lib (without the need to know about git.)
Use cases would include rescuing a project where somebody accidentally deleted the cache lib. (See current problems on the mailing list)

This might also be a good idea for people who work together on a project. They could say they all use the lib snapshot from Nov. 2017

In my mind this could be as simple as tagging the libs on a regular basis.

**Comment by SchrodingersGat** [comment]
Tagging the libs is a good way to achieve this. It could be the current stable KiCad release with an appended letter code e.g. 5.0.1c

Perhaps this can even be automated

**Comment by greyltc** [comment]
https://github.com/KiCad/kicad.github.io/pull/28 does this!

**Comment by greyltc** [comment]
PR #28 is merged and seems to work fine. I think this can be closed.
