### ISSUE TITLE
Split processing into multiple travis vm's

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad.github.io#16]
The last build errored because of an timeout (I restarted it to check if it completes now)

A simple idea to improve the build reliability would be to split symbol, footprint and 3d model parsing, and do it sequence. We could abuse https://docs.travis-ci.com/user/build-stages/ to do this.

A possible disatvantage of this would be that it's theroretically possible to have for example a kicad.github.io with up-to-date symbols, but old 3d-models

**Comment by pointhi** [comment]
hm, seems only 3d-models take so long. So probably not solvable by this technique

**Comment by SchrodingersGat** [comment]
The 3D model repo just doubled in size again. So it takes longer than Travis allows. What we need to do is only rebuild the bits that have changed since last build. Perhaps we should store the commit hash of each repository the last time that we built, or something along those lines.
