### ISSUE TITLE
comparing md5sums of compressed files

### ISSUE THREAD

**Issue by pointhi** [KiCad/kicad.github.io#17]
I saw the script checks if the md5sum of compressed files changes between builds. I expect this to be extremly unreliable. What about storing the commit id of the last checkout, and using git to determine if a directory was changed since last processing?

**Comment by SchrodingersGat** [comment]
I think this would work, not exactly sure how to implement it yet. Do you know why the MD5 approach doesn't work? I found it worked perfectly on my local machine but then not at all on Travis.

**Comment by SchrodingersGat** [comment]
I have now implemented this for the 3D models. It only rebuilds the model files that have changed.

This could also be implemented for the footprints and symbols

**Comment by SchrodingersGat** [comment]
This has now been implemented as you suggested
