### ISSUE TITLE
Legacy 3D model folders are not being deleted

### ISSUE THREAD

**Issue by SchrodingersGat** [KiCad/kicad.github.io#18]
The build script is not correctly purging 3D model directories that no longer exist in the repo.

**Comment by greyltc** [comment]
https://github.com/KiCad/kicad.github.io/pull/24 *might* fix this

**Comment by greyltc** [comment]
https://github.com/KiCad/kicad.github.io/pull/24 is merged. @SchrodingersGat, is this fixed now?

**Comment by SchrodingersGat** [comment]
It looks like this has done the job. Thanks
