### ISSUE TITLE
update issue with https://kicad.github.io/packages3d

### ISSUE THREAD

**Issue by greyltc** [KiCad/kicad.github.io#22]
The pages under https://kicad.github.io/packages3d are not being updated properly.

For example, https://kicad.github.io/packages3d/Converter_ACDC shows the text "Last updated on 20 October 2018" but the models listed there are not in sync with the gitgub 3d model repo as of Oct 20th.
eg. Converter_ACDC_RECOM_RAC04-xxSGx_THT.step has existed for almost a month in https://github.com/KiCad/kicad-packages3D but it's not shown in the table on https://kicad.github.io/packages3d/Converter_ACDC

**Comment by greyltc** [comment]
Nothing in https://github.com/KiCad/kicad.github.io/tree/master/_packages3d has changed in 3 months

**Comment by greyltc** [comment]
@poeschlr do you know what the problem is here?

**Comment by poeschlr** [comment]
I do not know what the issue is and i do not have time to investigate this at this point in time.

**Comment by greyltc** [comment]
@poeschlr Okay, bummer. Seems like maybe your commit adf2146c6fc12af730ac16bf774b0f0ac4378ce8 or around then broke it. Is there another maintainer of this repo that can look into this?

**Comment by poeschlr** [comment]
It did not work before that commit either. That is why i manually pushed the files back then.
I fear travis simply can not handle such a large build. (It ends in timeouts)

To be honest i am considering to change the download pages to have the latest stable release on them as i think a well made download page for them would be more important. Users who want cutting edge stuff would then be pointed to the github repo directly (downloading full repo as zip or even better using git itself.)
If we can not get travis to do it for us then i would say that a manual build for stable releases is reasonable. A continuous weekly build however really requires the automatic build stuff to work.

**Comment by greyltc** [comment]
Hmm. Can you point me to the travis build logs?

**Comment by poeschlr** [comment]
Latest log: https://api.travis-ci.org/v3/job/461060150/log.txt

**Comment by greyltc** [comment]
Yeah so, travis can't complete __a full re-build__ of the 3d packages library. This is because
A) the 3d parts library is huge
and
B) the compression options [specified here](https://github.com/KiCad/kicad.github.io/blob/d2b623e6a8c6777f1ca05671551740b26fe85b08/_scripts/zipper.py#L43) are extremely CPU intensive
This means the travis build takes more than 50 minutes and therefore gets killed.

@poeschlr, how would you feel about me making a PR that either changes the compression ratio or the archive type?

Alternatively, I'm trying to ask travis to use more threads for the compression but I doubt that's going to make enough of a difference.

**Comment by greyltc** [comment]
But I don't think that's the only issue here.

[This travis build](https://travis-ci.org/KiCad/kicad.github.io/builds/459274431) should have contained  all the incrimental changes in kicad-packages3D from November 23rd ( https://github.com/KiCad/kicad-packages3D/commit/0f228b438dd4b471363441ce36943bbef50f3bc1 through https://github.com/KiCad/kicad-packages3D/commit/e2863e780aad4ef37b62443d48f5c714ff354cba ) but [line 2057 of the associated build log](https://travis-ci.org/KiCad/kicad.github.io/builds/459274431#L2057) shows that none of the archives are being rebuilt despite the correct commit hashes being reported there so there also seems to be something wrong with the delta update logic as well.

**Comment by greyltc** [comment]
`git diff` here https://github.com/KiCad/kicad.github.io/blob/master/_scripts/gen_3dmodel_info.py#L73
will never work because the repo is a shallow clone with depth=1, the history just isn't there for this operation

A solution I can think of is using `git fetch --deepen <n>` enough times to get down to whatever is in https://github.com/KiCad/kicad.github.io/blob/master/_includes/commit_3d.html

**Comment by poeschlr** [comment]
Thanks for your effort. All of what you write above seems logical to me. However i am not an expert at these things so i can not really be of any assistance. As soon as you make a pull request i will take a quick look at it, push it and manually start travis to see if it works.

**Comment by greyltc** [comment]
This PR, https://github.com/KiCad/kicad.github.io/pull/24, won't really be tested properly until there are some changes in https://github.com/KiCad/kicad-packages3D for all the diff code to be properly exercised. There very well could be more bugs in there!

**Comment by poeschlr** [comment]
No problem. We have open pull requests to merge so test cases exist ;)

**Comment by greyltc** [comment]
So for testing purposes, it might be relevant to set [this line](https://github.com/KiCad/kicad.github.io/blob/master/_includes/commit_3d.html#L1) to be 2697052130a662aaf7483ebcb29d9d1fa18d2065 and then trigger a travis build.
That's one commit before the last manual build for the 3d shapes that took place ~ three months ago.

**Comment by poeschlr** [comment]
We might still have a problem. we still run into timeouts it seems:
https://api.travis-ci.org/v3/job/463581493/log.txt

**Comment by greyltc** [comment]
? I don't see a timeout there. Also a travis build timeout takes 50 minutes. I don't think we've had that long!

**Comment by poeschlr** [comment]
I see a line like this: /home/travis/.travis/job_stages: line 416:  5805 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"

Is this something else?

**Comment by greyltc** [comment]
yeah, no idea what those lines are, but they appear in successful builds too.
the log you've linked to ( https://api.travis-ci.org/v3/job/463581493/log.txt ) is from build #333 ([see here](https://travis-ci.org/KiCad/kicad.github.io/builds/463581492)) it completed successfully in 6 min 51 sec

Also, the travis robot seemed to push this commit here after that successful build: https://github.com/KiCad/kicad.github.io/commit/360658a7ac8f09e9b0810ef3c5261a922b0c06e5 so I'm pretty sure it's working.

**Comment by greyltc** [comment]
Try this PR: https://github.com/KiCad/kicad.github.io/pull/27 this one will take much longer and might timeout but it forces the repo to catch up on all the 3d parts changes it's missed in the last three months

**Comment by poeschlr** [comment]
new build triggered: https://travis-ci.org/KiCad/kicad.github.io/builds/463595747

**Comment by greyltc** [comment]
fingers crossed!

**Comment by poeschlr** [comment]
It seems to have been successful. Thanks again.

**Comment by greyltc** [comment]
Looks like the web site is up to date now too!
