### ISSUE TITLE
Cannot Print to Windows PDF in PCBNew

### ISSUE THREAD

**Issue by ejdprops** [KiCad/kicad.github.io#35]
Every time I try to print a PDF for fabrication, KiCad locks up.  It does the same with XPS.  PDF printer works fine in other programs, just not KiCad.

**Comment by cpresser** [comment]
Hi @ejdprops 

You did open this issue in the wrong issue tracker. This one is just for a part of the website. Not for the software itself.
Please head over to https://gitlab.com/kicad/code/kicad/

Thus, I am closing this issue.
